package com.tiansirk.countryquiz.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.firebase.firestore.Exclude;

import java.util.ArrayList;
import java.util.List;

/**
 * Model class for Firestore document: User
 */
public class User implements Parcelable {

    //The auto ID given by Firestore. It is needed to have during queries for identification, sorting, etc purposes
    private String documentId;  //needed only for to get the autogenerated ID from Firestore during query
    private String username;
    private int totalPoints;
    private List<Integer> completedLevels;
    private List<Level> levels;

    /** Empty constructor is needed for Firestore to be able to recreate the Object from its Document */
    public User() {
    }

    public User(String username, int totalPoints, List<Integer> completedLevels, List<Level> levels) {
        this.username = username;
        this.totalPoints = totalPoints;
        this.completedLevels = completedLevels;
        this.levels = levels;
    }

    //Need to be excluded from Firestore's autogenereting the Object
    @Exclude
    public String getDocumentId() {
        return documentId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getTotalPoints() {
        return totalPoints;
    }

    public void setTotalPoints(int totalPoints) {
        this.totalPoints = totalPoints;
    }

    public List<Integer> getCompletedLevels() {
        return completedLevels;
    }

    public void setCompletedLevels(List<Integer> completedLevels) {
        this.completedLevels = completedLevels;
    }

    public List<Level> getLevels() {
        return levels;
    }

    public void setLevels(List<Level> levels) {
        this.levels = levels;
    }

    @Override
    public String toString() {
        return "User{" +
                "documentId='" + documentId + '\'' +
                ", username='" + username + '\'' +
                ", totalPoints=" + totalPoints +
                ", completedLevels=" + completedLevels +
                ", levels=" + levels +
                '}';
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.documentId);
        dest.writeString(this.username);
        dest.writeInt(this.totalPoints);
        dest.writeList(this.completedLevels);
        dest.writeTypedList(this.levels);
    }

    protected User(Parcel in) {
        this.documentId = in.readString();
        this.username = in.readString();
        this.totalPoints = in.readInt();
        this.completedLevels = new ArrayList<Integer>();
        in.readList(this.completedLevels, Integer.class.getClassLoader());
        this.levels = in.createTypedArrayList(Level.CREATOR);
    }

    public static final Parcelable.Creator<User> CREATOR = new Parcelable.Creator<User>() {
        @Override
        public User createFromParcel(Parcel source) {
            return new User(source);
        }

        @Override
        public User[] newArray(int size) {
            return new User[size];
        }
    };
}
